stud = []

s1 = int(input("Enter student marks :"))
stud.append(s1)
s2 = int(input("Enter student marks :"))
stud.append(s2)
s3 = int(input("Enter student marks :"))
stud.append(s3)
s4 = int(input("Enter student marks :"))
stud.append(s4)
s5 = int(input("Enter student marks :"))
stud.append(s5)
s6 = int(input("Enter student marks :"))
stud.append(s6)
stud.sort()
print(stud)