a = set()

n1 = int(input("Enter number :"))
a.add(n1)
n2 = int(input("Enter number :"))
a.add(n2)
n3 = int(input("Enter number :"))
a.add(n3)
n4 = int(input("Enter number :"))
a.add(n4)
n5 = int(input("Enter number :"))
a.add(n5)
n6 = int(input("Enter number :"))
a.add(n6)
n7 = int(input("Enter number :"))
a.add(n7)
n8 = int(input("Enter number :"))
a.add(n8)
print(a)